#ifndef EMBEDDED_FILES_H
#define EMBEDDED_FILES_H

#include <QString>
#include <QFile>
#include <QDir>
#include <QCoreApplication>

static void ensureConfigFilesExist() {
    QString appDir = QCoreApplication::applicationDirPath();
    
    struct ConfigFile {
        QString name;
        const char* content;
    };
    
    ConfigFile files[] = {
        { "eku.txt", 
          R"XCA_EKU(#不要编辑此文件，而是使用PROFILE\Application Data\xca ku.txt
#用户设置目录的路径取决于
#操作系统和版本。
#XCA查找此文件的路径显示在
#XCA的“关于”对话框作为“用户设置路径”
#041专属 ------------------------------------------------------------------------------------------
1.3.6.1.4.1.60896
# Core Usage -------------------------------------------------------------------------------------
2.5.29.32.0
2.5.29.37.0
#换行
1.1
#换行
# SSL ---------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.1
1.3.6.1.5.5.7.3.2
#换行
1.1
#换行
#SSL
2.23.140.1.1
2.23.140.1.2.1
2.23.140.1.2.2
2.23.140.1.2.3
2.23.140.1.31
2.23.140.1.4.2 
2.23.140.1.3
2.23.140.1.5
2.23.140.2.1
2.23.140.3.1
2.23.140.41
2.23.140.42
2.16.156.112554.3
#换行
1.1
#换行
# Code Sign ---------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.3
2.23.140.1.4.1
1.3.6.1.4.1.311.61.1.1
1.3.6.1.4.1.311.10.3.39
1.3.6.1.4.1.311.10.3.5
1.3.6.1.4.1.311.10.3.7
1.3.6.1.4.1.311.10.3.6
1.3.6.1.4.1.311.10.3.8
#换行
1.1
#换行
# Email Sign --------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.4
1.3.6.1.4.1.311.21.19
#换行
1.1
#换行
# Document Signing --------------------------------------------------------------------------------
1.2.840.113583.1.1.5
1.3.6.1.4.1.311.10.3.12
#换行
1.1
#换行
# CA Server ---------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.8
1.3.6.1.5.5.7.3.9
#换行
1.1
#换行
# SSH ---------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.21
1.3.6.1.5.5.7.3.22
1.3.6.1.5.2.3.4
#换行
1.1
#换行
# MS EFS ------------------------------------------------------------------------------------------
1.3.6.1.4.1.311.10.3.4
1.3.6.1.4.1.311.10.3.4.1
1.3.6.1.4.1.311.10.3.11
#换行
1.1
#换行
# MS BitLocker ------------------------------------------------------------------------------------
1.3.6.1.4.1.311.67.1.1
1.3.6.1.4.1.311.67.1.2
#换行
1.1
#换行
# MS CA -------------------------------------------------------------------------------------------
1.3.6.1.4.1.311
1.3.6.1.4.1.311.21.1
1.3.6.1.4.1.311.21.5
1.3.6.1.4.1.311.21.3
1.3.6.1.4.1.311.21.4
1.3.6.1.4.1.311.21.6
1.3.6.1.4.1.311.21.2
1.3.6.1.4.1.311.21.10
1.3.6.1.4.1.311.10.3.3
#换行
1.1
#换行
# MS CA Signing -----------------------------------------------------------------------------------
1.3.6.1.4.1.311.10.3.1
1.3.6.1.4.1.311.10.3.2
1.3.6.1.4.1.311.10.3.9
1.3.6.1.4.1.311.10.3.10
1.3.6.1.4.1.311.10.3.13
#换行
1.1
#换行
# MS OBJ Signing ----------------------------------------------------------------------------------
1.3.6.1.4.1.311.2.1.21
1.3.6.1.4.1.311.2.1.22
#换行
1.1
#换行
# MS Media -----------------------------------------------------------------------------------------
1.3.6.1.4.1.311.10.5.1
1.3.6.1.4.1.311.10.6.1
1.3.6.1.4.1.311.10.6.2
#换行
1.1
#换行
# MS AD --------------------------------------------------------------------------------------------
1.3.6.1.4.1.311.20.2
1.3.6.1.4.1.311.20.2.1
1.3.6.1.4.1.311.20.2.2
1.3.6.1.4.1.311.20.2.3
#换行
1.1
#换行
# Send --------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.23
1.3.6.1.5.5.7.3.24
1.3.6.1.5.5.7.3.25
1.3.6.1.5.5.7.3.26
#换行
1.1
#换行
# CMC ---------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.27
1.3.6.1.5.5.7.3.28
1.3.6.1.5.5.7.3.29
1.3.6.1.5.5.7.3.30
#换行
1.1
#换行
# IPSEC -------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.5
1.3.6.1.5.5.7.3.6
1.3.6.1.5.5.7.3.7
1.3.6.1.5.5.8.2.2
1.3.6.1.5.5.7.3.17
)XCA_EKU" 
        },
        { "dn.txt", 
          R"XCA_DN(#不要编辑此文件，而是使用PROFILE\Application Data\xca\dn.txt
#用户设置目录的路径取决于
#操作系统和版本。
#XCA查找此文件的路径显示在
#XCA的“关于”对话框作为“用户设置路径”
C
ST
L
O
OU
CN
emailAddress
serialNumber
givenName
surname
title
initials
description
role
pseudonym
name
dnQualifier
generationQualifier
x500UniqueIdentifier
businessCategory
streetAddress
localityName
postalCode
jurisdictionL
jurisdictionST
jurisdictionC
)XCA_DN" 
        },
        { "oids.txt", 
          R"XCA_OIDS(# Do not edit this file, rather use PROFILE\Application Data\xca\oids.txt
# The path of the user settings directory depends on the
# operating system and version.
# The path where XCA looks for this file is shown in the
# "About" dialog of XCA as "User settings path"

# OID			short name      long name
# OID:						short name:					long name
# ================================================================================
# Core Usage -------------------------------------------------------------------------------------
2.5.29.32.0:				anyPolicy:					Any Policy
2.5.29.37.0:				anyExtendedUsage:			Any Extended Usage
# Subject Extend ---------------------------------------------------------------------------------
2.5.4.17:					postalCode:					postalCode
2.5.4.9:					streetAddress:				streetAddress
2.5.4.5:					serialNumber:				serialNumber
2.5.4.15:					businessCategory:			businessCategory
2.5.4.44:					generationQualifier:		Generation Qualifier
2.5.4.45:					x500UniqueIdentifier:		x500 Unique Identifier
2.5.4.65:					pseudonym:					Pseudonym(Other Name)
0.2.262.1.10.7.20:			nameDistinguisher: 			Name distinguisher
# MS Extend ---------------------------------------------------------------------------------------
1.3.6.1.4.1.311.60.2.1.1:	IncLocalityName: 			Inc Locality Name
1.3.6.1.4.1.311.60.2.1.2:	IncStateOrProvinceName: 	Inc Province Name
1.3.6.1.4.1.311.60.2.1.3: 	IncCountryName: 			Inc CountryName
# EV Extend ---------------------------------------------------------------------------------------
2.23.140.1.1:				evExtend:					Extended Validation (EV) Extend
2.16.156.112554.3:			EVServer:					Extended Validation (EV) Server Cert
2.23.140.1.3:				EVSign:						Extended Validation (EV) Code Signing
2.16.840.1.113730.1:		selfEV:						Certificates EV Extend
2.16.840.1.113730.4.1:		exportApproved:				Certificates EV Export Approved
# SSL ---------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.1:			serverAuth:					[SSL3] Server Auth
1.3.6.1.5.5.7.3.2:			clientAuth:					[SSL3] Client Auth
# Code Sign ---------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.3:			codeSigning:				[Code] Code Signing
2.23.140.1.4.1:				ptcsc:						[Code] Publicly-Trusted Code Signing Certificates
1.3.6.1.4.1.311.61.1.1:		msKernSign:					[Code] Microsoft Kernel Coding Signing
1.3.6.1.4.1.311.10.3.39:	msEVWHQL:					[Code] Microsoft EV WHQL Verification
1.3.6.1.4.1.311.10.3.5:		msWHQL:						[Code] Microsoft SYS WHQL Verification
1.3.6.1.4.1.311.10.3.7:		msWHQLOEM:					[Code] Microsoft OEM WHQL Verification
1.3.6.1.4.1.311.10.3.6:		msNT5C:						[Code] Microsoft NTSystem Component Verification
1.3.6.1.4.1.311.10.3.8:		msENTC:						[Code] Microsoft Embedded Component Verification
# Email Sign --------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.4:			emailProtection:			[Mail] Email Protection
1.3.6.1.4.1.311.21.19:		msDSER:						[Mail] Microsoft DS Email Replication
# Document Signing --------------------------------------------------------------------------------
1.2.840.113583.1.1.5:		adobePDFSigning:			[Docs] Adobe PDF Signing
1.3.6.1.4.1.311.10.3.12:	msofficeSigning:			[Docs] Microsoft Office Signing
# IPSEC -------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.5:			ipsecEndSystem:				[IPSE] IP Security End Entity
1.3.6.1.5.5.7.3.6:			ipsecTunnel:				[IPSE] IP Security Tunnel
1.3.6.1.5.5.7.3.7:			ipsecUser					[IPSE] IP Security User
1.3.6.1.5.5.8.2.2:			iKEIntermediate: 			[IPSE] IP security end entity
1.3.6.1.5.5.7.3.17:			ipsecIKE:					[IPSE] IP Security IKE Tunnel
# CA Server ---------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.8:			timeStamping:				[Time] Time Stamping
1.3.6.1.5.5.7.3.9:			OCSPSigning:				[OCSP] OCSP Signing
# SCVP --------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.10:			pkixKeyPurpose:				PKIX Key Purpose
1.3.6.1.5.5.7.3.11:			sbgpCertAAServerAuth:		SBGP Cert AAServer Auth
1.3.6.1.5.5.7.3.12:			scvpRes:					SCVP Responder
1.3.6.1.5.5.7.3.15:			SCVPS:						SCVP Server
1.3.6.1.5.5.7.3.16:			SCVPC:						SCVP Client
# RFC 4334 ----------------------------------------------------------------------------------------
1.3.6.1.5.2.3.5:        pkInitKDC:      				Signing KDC Response
1.3.6.1.5.5.7.3.13:			id-kp-eapOverPPP:			EAP Over PPP
1.3.6.1.5.5.7.3.14:			id-kp-eapOverLAN:			EAP Over LAN
1.3.6.1.5.5.7.3.18:			CAPWAPAC:					CAPWAP AC
1.3.6.1.5.5.7.3.19:			CAPWAPWTP:					CAPWAP WTP
1.3.6.1.5.5.7.3.20:			SIP:						SIP
# SSH ---------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.21:			sshc:						[SSH] SSH Client
1.3.6.1.5.5.7.3.22:			sshs:						[SSH] SSH Server
1.3.6.1.5.2.3.4:        pkInitClientAuth:     	[SSH] PKINIT Client Auth
# Send --------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.23:			sendRouter:					Send Router
1.3.6.1.5.5.7.3.24:			sendProxy:					Send Proxy
1.3.6.1.5.5.7.3.25:			sendOwner:					Send Owner
1.3.6.1.5.5.7.3.26:			sendProxyOwner:				Send Proxy Owner
# CMC ---------------------------------------------------------------------------------------------
1.3.6.1.5.5.7.3.27:			cmcCA:						CMC CA Extended Key Usage
1.3.6.1.5.5.7.3.28:			cmcRA:						CMC Registration Authorities Key Usage
1.3.6.1.5.5.7.3.29:			cmcArchive:					CMC Archive Servers Extended Key Usage
1.3.6.1.5.5.7.3.30:			BGPSEC:						BGP SEC
# MS EFS ------------------------------------------------------------------------------------------
1.3.6.1.4.1.311.10.3.4:		msEFS:						[EFS] Microsoft EFS System
1.3.6.1.4.1.311.10.3.4.1:	msEFSFR:					[EFS] Microsoft EFS File Recovery
1.3.6.1.4.1.311.10.3.11:	msKR:						[EFS] Microsoft Key Recovery
# MS BitLocker ------------------------------------------------------------------------------------
1.3.6.1.4.1.311.67.1.1:		driveEncryption:			[Bit] Microsoft BitLocker Drive Encryption
1.3.6.1.4.1.311.67.1.2:		dataRecoveryAgent:			[Bit] Microsoft BitLocker Data Recovery Agent
# MS CA -------------------------------------------------------------------------------------------
1.3.6.1.4.1.311:			msALL:						[MS CA] Microsoft All Usage
1.3.6.1.4.1.311.21.1:		MsCaV:						[MS CA] Microsoft CA Version
1.3.6.1.4.1.311.21.5:		msCAE:						[MS CA] Microsoft CA Exchange
1.3.6.1.4.1.311.21.3:		msCVB:						[MS CA] Microsoft CRL Virtual Base
1.3.6.1.4.1.311.21.4:		msCNP:						[MS CA] Microsoft CRL Next Publish
1.3.6.1.4.1.311.21.6:		msKRA:						[MS CA] Microsoft Key Recovery Agent
1.3.6.1.4.1.311.21.2:		msCPCH:						[MS CA] Microsoft Certsrv Previous Cert Hash
1.3.6.1.4.1.311.21.10:		msACP:						[MS CA] Microsoft Application Certificate Policy
1.3.6.1.4.1.311.10.3.3:		msSGC:						[MS CA] Microsoft Server Gated Crypto
# MS CA Signing -----------------------------------------------------------------------------------
1.3.6.1.4.1.311.10.3.1:		msCTLSign:					[MS CA] Microsoft CTL Signing
1.3.6.1.4.1.311.10.3.2:		msTSS:						[MS CA] Microsoft Time Stamp Signing
1.3.6.1.4.1.311.10.3.9:		msRLS:						[MS CA] Microsoft Root List Signer
1.3.6.1.4.1.311.10.3.10:	msQS:						[MS CA] Microsoft Qualified Subordination
1.3.6.1.4.1.311.10.3.13:	msLSV:						[MS CA] Microsoft Lifetime Signing	
# MS OBJ Signing ----------------------------------------------------------------------------------
1.3.6.1.4.1.311.2.1.21:		msCodeInd:					[MS OS] Microsoft Individual Object Signing
1.3.6.1.4.1.311.2.1.22:		msCodeCom:					[MS OS] Microsoft Commercial Object Signing
# MS Media -----------------------------------------------------------------------------------------
1.3.6.1.4.1.311.10.5.1:		msDRM:						[MS ME] Microsoft Digtial Right Verification
1.3.6.1.4.1.311.10.6.1:		msL:						[MS ME] Microsoft Licenses Client
1.3.6.1.4.1.311.10.6.2:		msLS:						[MS ME] Microsoft Licenses Server
# MS AD --------------------------------------------------------------------------------------------
1.3.6.1.4.1.311.20.2:		dom:						[MS AD] Microsoft Domain Controller
1.3.6.1.4.1.311.20.2.1:		msEA:						[MS AD] Microsoft Enrollment Agent
1.3.6.1.4.1.311.20.2.2:		msSmartcardLogin:			[MS AD] Microsoft Smart Card Logon
1.3.6.1.4.1.311.20.2.3:		msUPN:						[MS AD] Microsoft Universal Principal Name

1.3.6.1.4.1.37476.9000.173:	pikaRootCA:					[Pika] Pikachu Root CA
1.3.6.1.4.1.37476.9000.173.1:	pikaExtended:				[Pika] Pikachu Extended Validation

#041专属 --------------------------------------------------------------------------------------------------
1.3.6.1.4.1.60896:	041:	041CA

2.23.140.1.2 :Baseline Requirements
2.23.140.1.1:Extended Validation (EV) Extend
2.16.156.112554.3:Extended Validation (EV) Server Cert
2.23.140.1.2 :Baseline Requirements
2.23.140.1.4.1:[Code] Publicly-Trusted Code Signing 

2.23.140.1.2.1:DV SSL:Extended Validation (DV) SSL
2.23.140.1.2.2:OV SSL:Extended Validation (OV) SSL
2.23.140.1.2.3:EV SSL:Extended Validation (EV) SSL

2.23.140.1.31:Tor EV:[Tor]Extended Validation (.onion-EV)
2.23.140.1.4.2:ptts:[Time] Publicly-Trusted Time Stamping
2.23.140.1.5:pts:[Time] Publicly-Trusted S/MIME
2.23.140.2.1:TestEV:Extended Validation (Test)
2.23.140.3.1:EVci:[EV] Cabforganization Identifie
2.23.140.41:Tor ccsn:[Tor]Cabf CaSigningNonce
2.23.140.42:Torcasn:[Tor]Cabf-ApplicantSigningNonce
#换行符------------------------------------------------------------------------
1.1:xx:-------------------------------------------------------------------
)XCA_OIDS" 
        }
    };
    
    for (const auto& f : files) {
        QString path = appDir + QDir::separator() + f.name;
        QFile file(path);
        if (!file.exists()) {
            if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
                file.write(f.content);
                file.close();
            }
        }
    }
}

#endif // EMBEDDED_FILES_H
